### ISSUE TITLE
Xcode 8.1 (8B62) - eliminate warnings

### ISSUE THREAD

**Issue by neoneye** [koher/EasyImagy#11]
EasyImagy is a really cool project.

When I open in the current Xcode 8.1 I see 59 warnings.

**Comment by koher** [comment]
Thanks😃

I think it is because of the compiler's bugs.

The following code generates a warning.

```swift
extension Image where Pixel: RGBAType { // map
    public func map(_ transform: (RGBA) -> RGBA) -> Image<RGBA> {
        let zelf = self as! Image<RGBA> // Warning: Cast from 'Image<Pixel>' to unrelated type 'Image<RGBA>' always fails
        return zelf._map(transform)
    }
}
```

Though it says the cast "always fails", it succeeds when `Pixel` is `RGBA`.

I implemented those extensions for the performance. It is also possible to use `@_specialize` to avoid warnings. However I wonder if I should do it because

1. I think it is a bug of the compiler.
2. I am not sure if `@_specialize` is a public attribute, which is underscored.

So I delayed it.

**Comment by litoarias** [comment]
Hi @koher, 
I don't remove warnings, How to delete it? I am confused using @_specialize, do you help me?
Thanks for this library 😀 !!

**Comment by koher** [comment]
Hi @litoarias,
I removed those warnings ( 76947e75c13b9c73ab3593b51e4c6b7c80975abf ) using concrete constrained extensions introduced in Swift 3.1 😉

**Comment by litoarias** [comment]
Perfect, I will have to update XCode to use it .. thanks .. I will try it 🎉
