### ISSUE TITLE
Changing pixels in png's with transparent background fails

### ISSUE THREAD

**Issue by theneedyguy** [koher/EasyImagy#18]
Hi I am using your library currently to create a steganography tool for macOS using Swift.

Basically I write the message into the last bit of each RGB value (not altering Alpha).
When I try this on an Image that has a transparent background It won't keep the changed RGB values but just sets them all to 0 because the Alpha is set to 0. I can only change the RGB values if the Alpha is all the way up at 255 (which means no transparency).

Either it's a problem with my code or with your library/framework because I created the same program already in Python and in C# where I have had no problem writing values to the pixels if they have transparency.
C# code for reference: [https://paste.purpl3.net/16](https://paste.purpl3.net/16)
Python3 code for reference: [https://hider.purpl3.net/static/app.py](https://hider.purpl3.net/static/app.py)
These two projects encode and decode images and the resulting images / messages are compatible with the two programs. The Swift version can also generate Images that can be read by the C# and Python version but only if they are PNG's without transparency.

Can you maybe help me out? I tried so much already for 3 days straight...

What is weird is that when I write to the debug console the before and after pixels they are exactly what I want but they don't end up in the final image
Maybe I am not saving the images correctly? 

The Swfit project is [here](https://github.com/theneedyguy/hider-debug)
The class I am doing all the work in is [this](https://github.com/theneedyguy/hider-debug/blob/master/EncoderViewController.swift)

**Comment by koher** [comment]
Hi, the reason why you lose your modification on pixels with alpha is [premultiplied alpha](https://developer.apple.com/documentation/coregraphics/cgimagealphainfo/1454112-premultipliedlast). Because `UIImage` in iOS does not support non-premultiplied alpha, I implemented EasyImagy using premultiplied alpha. I am not sure if `NSImage` on macOS support non-premultiplied alpha because I am not familiar with macOS app development. It may be possible to load images with non-premultiplied alpha by modifying [here](https://github.com/koher/EasyImagy/blob/c8347fa81cbf736bd19961f864e1e7cb2e1cc92e/EasyImagy/ImageCoreGraphics.swift#L5-L41) and [here](https://github.com/koher/EasyImagy/blob/76947e75c13b9c73ab3593b51e4c6b7c80975abf/EasyImagy/ImageAppKit.swift#L5-L32). (Sorry, I don't have enough time to modify and test it now. I might be able to do it in a month.)

You may also have to modify the following part of your code though it is outside of EasyImagy. I might encode data with premultiplied alpha.
https://github.com/theneedyguy/hider-debug/blob/2ec51e0e216facddd4dc11368ad218fa76014368/EncoderViewController.swift#L232-L259

**Comment by theneedyguy** [comment]
Hey thanks for your help. I will check out your recommendations. If I succeed I will let you know otherwise I hope to hear from you in a month or so :) Thx 👍

**Comment by theneedyguy** [comment]
Hey, just checking in to say that I haven't been able to figure something out and it's been a while past over a month since I last heard from you :)

**Comment by koher** [comment]
@theneedyguy 

Hi, I've tried it but it seems impossible to load images with non-premultiplied alpha even for macOS using CoreGraphics. Although `CGImageAlphaInfo` has [a property](https://developer.apple.com/documentation/coregraphics/cgimagealphainfo/1454550-last) named (non-premultiplied) `last`, it seems not to be supported. The table 2-1 in [this page](https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_context/dq_context.html#//apple_ref/doc/uid/TP30001066-CH203-TPXREF101) shows supported formats for iOS and macOS.

It is possible to load images with non-premultiplied alpha using another library, e.g. libpng, instead CoreGraphics. However it adds a dependency to EasyImagy and I want to avoid it. `canImport` introduced in Swift 4.1 may make it possible to support non-premultiplied alpha only when libpng is available.
