### ISSUE TITLE
helpers for  Image<RGBA<UInt8>> -> byte array of [Uint8]

### ISSUE THREAD

**Issue by johndpope** [koher/EasyImagy#33]
how to flatten out image to an array of uint 8 pixels? 
Is there a helper - I'm not worried about expense of copying. 

```swift
typealias Byte = UInt8

extension Image where Pixel == UInt8 {
    func byteArray()->[Byte]{
        var pixelIterator = self.makeIterator()
        var pixelArray:[Byte] = []
        while let pixel = pixelIterator.next() {
            pixelArray.append(pixel)
        }
        return pixelArray
    }
}


```

**Comment by johndpope** [comment]
extension Image where Pixel == RGBA<UInt8>
{
    func grayScale()->[UInt8]{
        return  self.map { $0.gray }
    }

}

**Comment by koher** [comment]
Sorry for replying so late.

Because the `Image` conforms to the `Sequence`, you can write it in the following way.

```swift
let image: Image<UInt8> = Image(width: 3, height: 2, pixels: [0, 1, 2, 3, 4, 5])
let pixels: [UInt8] = image.map { $0 } // [0, 1, 2, 3, 4, 5]
```

If the array is used temporarily, `withUnsafeBytes` or `withUnsafeBufferPointer` do it in better performance because they avoid copying the whole image, which can be used in the same way as the `Array`'s ones.

```swift
let image: Image<UInt8> = Image(width: 3, height: 2, pixels: [0, 1, 2, 3, 4, 5])
image.withUnsafeBytes { (pointer: UnsafeRawBufferPointer) in
    print(pointer[0]) // 0
    print(pointer[5]) // 5
    print(pointer.count) // 6
}
```

```swift
let image: Image<UInt8> = Image(width: 3, height: 2, pixels: [0, 1, 2, 3, 4, 5])
image.withUnsafeBufferPointer { (pointer: UnsafeBufferPointer<UInt8>) in
    print(pointer[0]) // 0
    print(pointer[5]) // 5
    print(pointer.count) // 6
}
```

You can also use `withUnsafeMutableBytes` and `withUnsafeMutableBufferPointer` when images are mutable ( `var image` ).

**Comment by johndpope** [comment]
Thanks
