### ISSUE TITLE
Slower on iOS 13

### ISSUE THREAD

**Issue by ericjohns55** [koher/EasyImagy#51]
I have noticed since updating to iOS 13 from 12.4.1, the library has been running a lot slower than it was before. I used to consistently clock in around 250ms to flip an image over the x-axis, but now it is constantly at 3.1 seconds for the same exact image. Many other built in functions are slower as well. I tried updating Xcode to 11, Swift to 5, and the library itself to 0.7.0 but nothing has helped, and the code has not changed. Has anyone else had this issue or found a solution?

**Comment by koher** [comment]
Thank you for reporting the issue.

> I used to consistently clock in around 250ms to flip an image over the x-axis, but now it is constantly at 3.1 seconds for the same exact image.

Can you share the code to reproduce it? I guess you used `image.xReversed()`. How large was the image? Which optimization level did you use? `-Onone` / `-O` / `-Osize` / `-Ounchecked`

Did it happen on a device? Does it also happen on a simulator?

On a simulator, CI shows that running on iOS 13 is a little slower than on iOS 12. However, I can't judge if it is caused by iOS 13. It may be by accident or the difference of the simulated device: iPhone XS or iPhone 11 Pro.

**Xcode 10.2, iOS 12.2, iPhone XS**
https://travis-ci.org/koher/swift-image/jobs/588113369
```
$ xcodebuild test -scheme SwiftImage-iOS -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c

...
HigherOrderFunctionsTests
    ✓ testMap (0.001 seconds)
    ◷ testMapPerformance measured (0.014 seconds)
    ✓ testMapPerformance (0.753 seconds)
    ✓ testUpdate (0.002 seconds)
    ◷ testUpdatePerformance measured (0.001 seconds)
    ✓ testUpdatePerformance (1.535 seconds)
```

**Xcode 11, iOS 13.0, iPhone 11 Pro**
https://travis-ci.org/koher/swift-image/jobs/588113370

```
$ xcodebuild test -scheme SwiftImage-iOS -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty -c
...
HigherOrderFunctionsTests
    ✓ testMap (0.001 seconds)
    ◷ testMapPerformance measured (0.018 seconds)
    ✓ testMapPerformance (1.102 seconds)
    ✓ testUpdate (0.001 seconds)
    ◷ testUpdatePerformance measured (0.003 seconds)
    ✓ testUpdatePerformance (2.017 seconds)
```

The difference seems much less than you reported although the test cases does not include a performance test for `xReverse` of a large image and I am not sure if the issue is reproduced on a simulator.

**Comment by ericjohns55** [comment]
I have been running the following code:
```swift
var image = Image<RGBA<UInt8>>(named: "tree")!
image = image.xReversed()
self.imageView.image = image.uiImage
```

I am not running on any optimization level but I would be interested in learning how to use one of them.

It runs much faster (~1.6) seconds by not putting it in the image view, even though it still ran at 250ms earlier with the flip and putting in the imageview before.

I have been testing the program on an iPhone 7+ and tried it a few times on an iPhone X with similar results. The program also runs much slower on the emulator than on a device.

The image I have been testing on is 1024x715 and I attached it down below:
![tree](https://user-images.githubusercontent.com/10274863/66345885-f3cb7a00-e91e-11e9-964f-f74c4f6e2730.png)

**Comment by ericjohns55** [comment]
After getting a developer account and exporting the app as ad hoc, the speed of the app went back to about the way it was before even though the optimization level between debug and release is the same. Not sure whats causes the development versions to run so much slower but everything runs smoothly now.
