### ISSUE TITLE
Very slow performance on initialization and resizing

### ISSUE THREAD

**Issue by yarivadam** [koher/EasyImagy#54]
Hi,
I've been trying to load an image (attached) (1.9MB, 2162 × 3843), crop it and then resize the results. It's working, but taking about 30 seconds for the process!
I've seen a closed issue regarding performance in iOS 13, but I've compiled with speed optimizations and I see no change. Here's the code I'm running, along with the time it takes:
Creating image data for image of size: (2162.0, 3843.0):
   Code: let imageData = Image<RGBA<UInt8>>(uiImage: image!) ; Time: 6.934875965118408 s
Cropping photo ( 0 < x < 2161, 1316 < y < 2525)
   Code: let croppedImageData = Image<RGBA<UInt8>>(data[minX..<maxX, minY..<maxY]) ; Time: 1.0871039628982544
resizing photo to: 2736.0 by 1530.0
   Code: let resizedCroppedImageData = croppedImageData.resizedTo(width: 2736, height: 1530) ; Time: 22.0144259929657

My Compiler settings: Optimization level [-O] (Swift compiler - code generation), [-Ofast] (Apple CLang - Code Generation)

The machine I'm running on: iPhone XS, iOS 13.5.1

Is there anything I'm doing wrong? Any help would be appreciated!

![18052DE9-661F-4E53-8EFE-24DF60D45282](https://user-images.githubusercontent.com/16579840/84474753-0fe49f80-ac94-11ea-9618-265052d111ee.jpeg)

**Comment by koher** [comment]
Sorry for my late response. Thank you for posting the issue. I have missed your post. I will investigate and reply in this weekend.

**Comment by yarivadam** [comment]
Thanks, looking forward to it!

**Comment by koher** [comment]
In my environment (iPhone X with iOS 13.5, `-O` with whole module optimizations), the code ran much faster.

| API | time(s) |
|:--|:--|
| `init(uiImage:)` | 2.03 |
| `init(_:)` (converting to `Image` after cropping) | 0.178 |
| `resizedTo(width:height:)` | 7.46 |

<img width="693" alt="load-image-performance" src="https://user-images.githubusercontent.com/217100/85936714-087df100-b938-11ea-8075-c1d012329c1a.png">

https://github.com/koher/swift-image-performance-experiment

Could you check how long it takes that the code in the repo above runs in your environment?

Anyway, it is still slow that resizing takes 7.46 seconds. Because, for now, SwiftImage's `resizeTo` method is implemented naively. As an option, you can also resize images much faster combining SwiftImage with Core Image like the code below.

```swift
let image = Image<RGB<UInt8>>(uiImage: inputImage)
let xRange = 1 ..< 2161
let yRange = 1316 ..< 2525
let cropped = Image(image[xRange, yRange])
let outputImage: UIImage = cropped.withCGImage { cgImage in
    let ciImage = CIImage(cgImage: cgImage)
    
    let filter = CIFilter(name: "CILanczosScaleTransform")!
    filter.setValue(ciImage, forKey: kCIInputImageKey)
    let scale = NSNumber(value: 2736.0 / Double(cropped.width))
    filter.setValue(scale, forKey: kCIInputScaleKey)
    filter.setValue(NSNumber(value: 1.0 as Float), forKey: kCIInputAspectRatioKey)
    let output = filter.value(forKey: kCIOutputImageKey) as! CIImage
    let context = CIContext(options: [.useSoftwareRenderer: false])
    return UIImage(cgImage: context.createCGImage(output, from: output.extent)!)
}
```

It takes only 0.312 seconds for whole process.

<img width="705" alt="load-image-performance-with-core-image" src="https://user-images.githubusercontent.com/217100/85937380-da031480-b93d-11ea-8091-05107e34c744.png">

https://github.com/koher/swift-image-performance-experiment/tree/core-image

I will consider to use Core Image for resizing and other operations when it is available (environments, pixel types and so on) and the algorithm for the operation is not explicitly specified by the user.

Thanks!

**Comment by yarivadam** [comment]
Thanks for the reply! I haven't tested the code in the repo, but as you noted, even in the best case it's pretty slow. Your suggestion about using Core Graphics really helped me, and now it runs much faster. Thanks again!
